name: WSO2 API CI/CD
on:
  push:
    paths:
      - 'dev/**'
      - 'ShopKartProductAPI/**'
      - '.github/workflows/dev-shopkart-api-pipeline.yml'
    branches:
      - main

jobs:
  deploy-api-dev:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'dev') || github.event_name == 'push' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add etc/hosts entry for dev.airbus.am.wso2.com ðŸŒ
        run: |
          # Format: IP Address    Hostname(s)
          # 'tee -a' appends the line to /etc/hosts using sudo privileges.
          echo '20.6.64.200 dev.airbus.am.wso2.com' | sudo tee -a /etc/hosts
          
          # Optional: Verify the entry
          echo "Hosts file content after addition:"
          cat /etc/hosts

      - name: Install apictl
        run: |
          wget https://github.com/wso2/product-apim-tooling/releases/download/v4.6.0/apictl-4.6.0-linux-amd64.tar.gz
          tar -xzf apictl-4.6.0-linux-amd64.tar.gz
          chmod +x apictl/apictl
          sudo mv apictl/apictl /usr/local/bin/

      - name: Add Dev Environment
        run: |
          apictl add env dev --apim https://${{ secrets.WSO2_DEV_APIM }}

      - name: Login to Dev
        run: |
          apictl login dev -u ${{ secrets.APIM_USERNAME }} -p ${{ secrets.APIM_PASSWORD }} --insecure

      - name: Import API to Dev
        run: |
          apictl import api -f dev/ShopKartProductAPI/ -e dev --preserve-provider=false --update --insecure

      - name: Run Tests (Optional)
        run: |
          apictl get apis -e dev --insecure | awk 'NR>1 {print}' | grep -E "ShopKartProductAPI" || {
            echo "ShopKartProductAPI not found in Publisher (dev)."
            exit 1
          }
          echo "ShopKartProductAPI is present in Publisher (dev)"